"""ABCD pseudo clinical concept auto-labeling using classical image processing.

Computes four concepts from a lesion image + its segmentation mask:

  A — Asymmetry       : SSIM between left/right halves, 1 - SSIM in [0,1]
  B — Border          : Isoperimetric ratio (P²/4πA), normalized to [0,1]
  C — Color variation : HSV entropy within lesion mask, normalized to [0,1]
  D — Normalized Area : Lesion pixel count / total image pixels, in [0,1]
                         Also estimates diameter in mm using calibrated FOV.

All functions are deterministic, vectorized with OpenCV/scikit-image,
and unit-tested with synthetic examples.

Terminology: These are "Pseudo Clinical Concepts" — auto-generated by
classical CV, not manually annotated by dermatologists.
"""

import os
from pathlib import Path
from typing import Dict, Tuple, Optional

import numpy as np
import cv2
from skimage.metrics import structural_similarity as ssim


def compute_asymmetry(mask: np.ndarray) -> float:
    """Compute left-right asymmetry score of the lesion mask.

    Reflects the lesion mask across its vertical midpoint and computes
    the SSIM between the two halves. Score = 1 - SSIM, so perfectly
    symmetric lesions score near 0, highly asymmetric near 1.

    Args:
        mask: Binary mask (H, W) with values in {0, 255} or {0, 1}.

    Returns:
        Asymmetry score in [0, 1].
    """
    if mask.max() <= 1:
        mask = (mask * 255).astype(np.uint8)
    else:
        mask = mask.astype(np.uint8)

    h, w = mask.shape
    if h == 0 or w == 0:
        return 0.0

    mid = w // 2
    left = mask[:, :mid]
    right_flipped = mask[:, w - 1:w - mid - 1:-1]

    mh_left = min(left.shape[1], right_flipped.shape[1])
    left_cropped = left[:, :mh_left]
    right_cropped = right_flipped[:, :mh_left]

    if left_cropped.size == 0:
        return 0.0

    left_f = left_cropped.astype(np.float32) / 255.0
    right_f = right_cropped.astype(np.float32) / 255.0

    try:
        ssim_val, _ = ssim(left_f, right_f, full=True,
                            data_range=1.0,
                            win_size=min(7, min(mh_left, h)))
        if np.isnan(ssim_val):
            return 0.0
        score = 1.0 - ssim_val
        return float(np.clip(score, 0.0, 1.0))
    except Exception:
        overlap = np.mean(left_f * right_f) / (np.mean(left_f) * np.mean(right_f) + 1e-8)
        score = 1.0 - min(float(overlap), 1.0)
        return float(np.clip(score, 0.0, 1.0))


def compute_border_irregularity(mask: np.ndarray) -> float:
    """Compute border irregularity via isoperimetric ratio.

    ratio = perimeter² / (4 * PI * area)
    Perfect circle => ratio = 1.0; more irregular => ratio > 1.
    Normalized to [0, 1] via: 1 - exp(-k * (ratio - 1))
    where k = 2.0 provides good separation.

    Args:
        mask: Binary mask (H, W).

    Returns:
        Border irregularity score in [0, 1].
    """
    if mask.max() <= 1:
        mask_bin = (mask > 0.5).astype(np.uint8)
    else:
        mask_bin = (mask > 127).astype(np.uint8)

    contours, _ = cv2.findContours(mask_bin, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return 0.0

    largest = max(contours, key=cv2.contourArea)
    area = cv2.contourArea(largest)
    perimeter = cv2.arcLength(largest, True)

    if area < 1.0 or perimeter < 1.0:
        return 0.0

    ratio = (perimeter * perimeter) / (4.0 * np.pi * area)
    k = 2.0
    score = 1.0 - np.exp(-k * (max(ratio, 1.0) - 1.0))
    return float(np.clip(score, 0.0, 1.0))


def compute_color_variation(image: np.ndarray, mask: np.ndarray) -> float:
    """Compute color variation via HSV Shannon entropy within the lesion.

    Builds a 3D histogram (H:16 bins, S:4 bins, V:4 bins) and computes
    Shannon entropy, normalized by log2(number of bins) for [0,1] range.

    Args:
        image: RGB image (H, W, 3), uint8.
        mask: Binary mask (H, W).

    Returns:
        Color variation score in [0, 1].
    """
    if mask.max() <= 1:
        mask_bin = (mask > 0.5).astype(np.uint8)
    else:
        mask_bin = (mask > 127).astype(np.uint8)

    if image.dtype != np.uint8:
        image = (np.clip(image, 0, 255)).astype(np.uint8)

    hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
    pixels = hsv[mask_bin > 0]
    if len(pixels) < 10:
        return 0.0

    h_bins, s_bins, v_bins = 16, 4, 4
    hist, _ = np.histogramdd(
        pixels,
        bins=[h_bins, s_bins, v_bins],
        range=[(0, 180), (0, 256), (0, 256)],
    )
    hist = hist.flatten()
    total = hist.sum()
    if total == 0:
        return 0.0
    probs = hist / total
    probs = probs[probs > 0]
    entropy = -np.sum(probs * np.log2(probs))
    max_entropy = np.log2(h_bins * s_bins * v_bins)
    score = entropy / max_entropy if max_entropy > 0 else 0.0
    return float(np.clip(score, 0.0, 1.0))


def compute_normalized_area(mask: np.ndarray, img_size: int = 224) -> Tuple[float, float]:
    """Compute normalized lesion area and estimated diameter in mm.

    Normalized area = lesion_pixel_count / total_image_pixels (in [0, 1]).
    Estimated diameter (mm) = sqrt(lesion_area_pixels) * scale_factor_mm_per_pixel.

    Uses a default dermoscopic field-of-view of ~12mm for a 224x224 image
    when no calibration is available.

    Args:
        mask: Binary mask (H, W).
        img_size: Image width/height in pixels (default 224).

    Returns:
        (normalized_area, diameter_mm): Both floats.
    """
    if mask.max() <= 1:
        mask_bin = (mask > 0.5).astype(np.uint8)
    else:
        mask_bin = (mask > 127).astype(np.uint8)

    total_pixels = img_size * img_size
    lesion_pixels = int(mask_bin.sum())

    normalized_area = lesion_pixels / total_pixels

    default_fov_mm = 12.0
    mm_per_pixel = default_fov_mm / img_size
    diameter_mm = 2.0 * np.sqrt(lesion_pixels / np.pi) * mm_per_pixel if lesion_pixels > 0 else 0.0
    diameter_mm = min(diameter_mm, 20.0)

    return float(np.clip(normalized_area, 0.0, 1.0)), float(diameter_mm)


def compute_all_abcd(
    image: np.ndarray,
    mask: np.ndarray,
    img_size: int = 224,
) -> Dict[str, float]:
    """Compute all four ABCD pseudo clinical concepts from an image and its mask.

    Args:
        image: RGB image (H, W, 3), uint8.
        mask: Binary mask (H, W), uint8 or bool.
        img_size: Image width/height in pixels.

    Returns:
        Dict with keys: asymmetry, border, color, normalized_lesion_area, diameter_mm.
    """
    asymmetry = compute_asymmetry(mask)
    border = compute_border_irregularity(mask)
    color = compute_color_variation(image, mask)
    area_norm, diameter_mm = compute_normalized_area(mask, img_size)

    return {
        "asymmetry": asymmetry,
        "border": border,
        "color": color,
        "normalized_lesion_area": area_norm,
        "diameter_mm": diameter_mm,
    }


def load_mask(mask_path: str, img_size: int = 224) -> np.ndarray:
    """Load a binary segmentation mask from disk, resizing to img_size."""
    mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
    if mask is None:
        return np.zeros((img_size, img_size), dtype=np.uint8)
    if mask.shape[:2] != (img_size, img_size):
        mask = cv2.resize(mask, (img_size, img_size), interpolation=cv2.INTER_NEAREST)
    return mask


def load_image(image_path: str, img_size: int = 224) -> np.ndarray:
    """Load an RGB image from disk, resizing to img_size."""
    img = cv2.imread(str(image_path))
    if img is None:
        return np.zeros((img_size, img_size, 3), dtype=np.uint8)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    if img.shape[:2] != (img_size, img_size):
        img = cv2.resize(img, (img_size, img_size))
    return img
